/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sniffer;

import java.awt.EventQueue;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.Clock;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.scene.control.SelectionMode;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.SwingWorker;
import javax.swing.Timer;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import jpcap.packet.Packet;
import org.jnetpcap.packet.PcapPacket;
import static sniffer.Statistical_Analysis.con;

/**
 *
 * @author Rishabh
 */
public class User_Interface extends javax.swing.JFrame {
    public static PcapPacket[] p=new PcapPacket[1000000];
    private SwingWorker sw,dw;
    public static boolean capture=true;
    public static int i=0;
    public static Date current_time;
    static Timer t;
    static  int till_now=0;
    /**
     * Creates new form User_Interface
     */
    public User_Interface() {
 
       initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jToggleButton1 = new javax.swing.JToggleButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(620, 700));
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(null);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 20, 290, 110);

        jLabel1.setText("Please select the device from the list only..");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 0, 290, 14);

        jButton1.setText("List");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(310, 30, 70, 23);
        jPanel1.add(jTextField1);
        jTextField1.setBounds(310, 70, 70, 20);

        jButton2.setText("Select");
        jButton2.setEnabled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(310, 100, 73, 23);

        jButton3.setText("GO");
        jButton3.setEnabled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(390, 100, 47, 23);

        jButton4.setText("STOP");
        jButton4.setEnabled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(440, 100, 59, 23);

        jButton5.setText("STORE");
        jButton5.setEnabled(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(510, 100, 65, 23);
        jPanel1.add(jTextField2);
        jTextField2.setBounds(450, 30, 60, 20);

        jLabel2.setText("FileName");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(390, 30, 60, 20);

        jButton6.setText("Set");
        jButton6.setEnabled(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);
        jButton6.setBounds(520, 30, 49, 23);

        jLabel3.setText("Filter");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(390, 70, 24, 14);
        jPanel1.add(jTextField3);
        jTextField3.setBounds(430, 70, 60, 20);

        jToggleButton1.setText("FILTER");
        jPanel1.add(jToggleButton1);
        jToggleButton1.setBounds(500, 70, 70, 23);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 20, 580, 140);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Source", "Destination"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable1MousePressed(evt);
            }
        });
        jTable1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jTable1PropertyChange(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jPanel2.add(jScrollPane2);
        jScrollPane2.setBounds(10, 10, 560, 190);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane3.setViewportView(jTextArea2);

        jPanel2.add(jScrollPane3);
        jScrollPane3.setBounds(10, 210, 560, 180);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(10, 160, 580, 420);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
Start.listNetworkInterfaces();
jButton2.setEnabled(true);

        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
Start.go(Integer.parseInt(jTextField1.getText()));
jButton6.setEnabled(true);
jTextField1.setEnabled(false);
jButton2.setEnabled(false);
// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed
static DefaultTableModel dtm;
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
//p=new PcapPacket[1000000];
current_time=new Date(System.currentTimeMillis());
       jButton3.setEnabled(false);

i=0;
jTextArea2.setText("");

        dtm=new DefaultTableModel(new String[]{"Packet No","Source","Destination"},0);
jTable1.setModel(dtm);
jTable1.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
    
    @Override
    
    public void valueChanged(ListSelectionEvent e) {
    EventQueue.invokeLater(new Runnable() {
        @Override
        public void run() {
             if(jTable1.getSelectedRow()!=-1)
       { 
           
           jTextArea2.setText("");
           jTextArea2.append(p[jTable1.getSelectedRow()].toString());
           jTextArea2.setCaretPosition(0);
       } 
            //To change body of generated methods, choose Tools | Templates.
        }
    });
        
    }
});
//Statistical_Analysis.packet_per_second=new int[1000000];
//Statistical_Analysis.packet_size=new int[1000000][5];
dw=new Packet_Dumper_Thread();
dw.execute();

Applogger applog=new Applogger();
Thread t1=new Thread(applog.new netstat(filename));
Thread t2=new Thread(applog.new tasklist(filename));
t1.start();
t2.start();
jButton4.setEnabled(true);

// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        capture=false;
        Packet_Dumper_Thread.pcap.breakloop();
        dw.cancel(true);
        dw=null;
        sw=new Packet_Capture_Thread(dtm);
        sw.execute();
        jButton3.setEnabled(true);
        jButton4.setEnabled(false);
        jButton5.setEnabled(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTable1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jTable1PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1PropertyChange

    private void jTable1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MousePressed
    // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MousePressed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
new Statistics_Interface().setVisible(true);
        
        try {
            Statistical_Analysis.anal(filename);
            
            
// TODO add your handling code here:
        } catch (SQLException ex) {
            Logger.getLogger(User_Interface.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton5ActionPerformed
public static String filename="";

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed

      // TODO add your handling code here:
        
        filename=jTextField2.getText();
        
        try {
            Class.forName("com.mysql.jdbc.Driver");
          Connection  con1 = DriverManager.getConnection("jdbc:mysql://localhost:3306/network_anal", "root", "admin");
            Statement stmt = con1.createStatement();
            //stmt.execute("Insert into network_anal values("+);
            stmt.execute("create table "+filename+"_packetinfo(id Integer,size Integer, ETHERNET Integer,IPv4 Integer, IPv6 Integer, TCP Integer, UDP Integer,HTTP Integer ,HTTPS Integer,ARP Integer, ICMP Integer, PPP Integer)");
            stmt.execute("create table "+filename+"_flagsvalue(id Integer,MF Integer,CWR Integer, ECN Integer, URG Integer, ACK Integer, PSH Integer, RST Integer,SYN Integer,FIN Integer)");
            stmt.execute("create table "+filename+"_flow(id Integer, time numeric(12),source_ip varchar(30),source Integer,direction Integer,Destination Integer, Dest_ip varchar(30),Comment varchar(30), Stream Integer)");
            stmt.execute("create table "+filename+"_seqack(id Integer, seqno numeric(15), ackno numeric(15), estb Integer)");
            stmt.execute("create table "+filename+"_netstat(source_add varchar(30),source_port varchar(8),dest_add varchar(30),dest_port varchar(8),pid varchar(10),primary key(source_add,source_port,pid))");
            stmt.execute("create table "+filename+"_tasklist(appname varchar(30),pid varchar(10),primary key(appname,pid))");
        } catch (Exception e) {
            e.printStackTrace();
        }
        jTextField2.setEnabled(false);
        jButton3.setEnabled(true);
        jButton4.setEnabled(true);
        
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(User_Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(User_Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(User_Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(User_Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new User_Interface().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    public static javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    public static javax.swing.JTable jTable1;
    public static javax.swing.JTextArea jTextArea1;
    public static javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    public static javax.swing.JTextField jTextField3;
    public static javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
